AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  ACMCertArn:
    Type: String
    Description: This is the ACM arn
  SiteURL:
    Type: String
    Description: This is the URL of the site
  ZoneName:
    Type: String
    Description: This is the ZoneName of the SiteURL

Outputs:
  StandbyHealthCheckId:
    Description: "Physical ID of healthcheck"
    Value: !Ref StandbyHealthCheck
  StandbyReplBucketArn:
    Description: "Full S3 Bucket Arn"
    Value: !Join [ "", [ 'arn:aws:s3:::' , !Ref StandbyReplicationBucket ] ]
  CloudFrontDistributionDomainName:
    Description: Domain Name
    Value: !GetAtt StandbyCloudFrontDistribution.DomainName
  CloudFrontDistributionID:
    Description: CF ID
    Value: !Ref StandbyCloudFrontDistribution

Resources:
  StandbyReplicationBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    Properties:
      VersioningConfiguration:
        Status: Enabled

  StandbyHealthCheck:
    Type: "AWS::Route53::HealthCheck"
    Properties:
      HealthCheckConfig:
        FullyQualifiedDomainName: !Join [ '.', [ !Join [ '-', [ "s3", !Ref "AWS::Region" ] ], "amazonaws.com" ] ]
        Type: "HTTP"
        ResourcePath: !Join [ '/', [ '', !Ref 'StandbyReplicationBucket', 'index.html' ] ]
      HealthCheckTags:
        - Key: "Name"
          Value: "StandbyBucketHealthCheck"

  StandbyCloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Aliases:
          - !Ref SiteURL
        Comment: StandbyCloudFrontDistribution
        DefaultCacheBehavior:
          ForwardedValues:
            QueryString: false
          TargetOriginId: StandbyBucketOrigin
          ViewerProtocolPolicy: redirect-to-https
        DefaultRootObject: index.html
        Enabled: true
        HttpVersion: http2
        Origins:
        - DomainName: !Join [ '.', [ !Ref StandbyReplicationBucket, 's3.amazonaws.com' ] ]
          Id: StandbyBucketOrigin
          S3OriginConfig:
            OriginAccessIdentity: ""
        PriceClass: PriceClass_100
        ViewerCertificate:
          AcmCertificateArn: !Ref ACMCertArn
          SslSupportMethod: sni-only
  Route53Stack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.amazonaws.com/static-s3-region-failure-artifacts/nested-route53.yml
      Parameters:
        ZoneName: !Ref ZoneName
        SiteURL: !Ref SiteURL
        AliasTargetDNSName: !GetAtt StandbyCloudFrontDistribution.DomainName
